
#  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
spring:
  datasource:

    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/bank"
    username: "root"
    password: "1234"



  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
     hibernate:
       type: trace


